[package]
name = "trtllm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
cxx = { version = "1.0", features = ["c++20"] }

[dev-dependencies]
tokenizers = "0.21"

[build-dependencies]
cxx-build = "1.0"